### ISSUE TITLE
Remove region replication before secret deletion

### ISSUE THREAD

**Issue by jmcruz1983** [usmansaleem/aws-sm-migrator#14]
Hi there,
currently when having secrets replication,
migration tool cannot delete the secrets
as per following logs:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Fetching secrets under prefix web3signer-aws-integration/
Fetched 10 secrets
.....
Fetched 10 secrets
Deleting web3signer-aws-integration/<REDACTED>
You can't delete secret arn:aws:secretsmanager:eu-north-1:<REDACTED>:secret:web3signer-aws-integration/<REDACTED> that still has replica regions [eu-central-1].
```

Can we add CLI argument to delete command to remove replication before deleting each secret?

An example of aws cli :

https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/remove-regions-from-replication.html

```
apiVersion: batch/v1
kind: Job
metadata:
  name: awscli-test-remove-replication
  namespace: test
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: awscli-delete
        image: amazon/aws-cli
        args:
          - secretsmanager
          - remove-regions-from-replication
          - --remove-replica-regions=eu-central-1
          - --secret-id=web3signer-aws-integration/<REDACTED>
```

Thanks
